export const products = [
  {
    id: 1,
    src: "./assets/angry.png",
    alt: "Angry man",
    name: "Anger",
    description: "Description: Be angry with ANOTHER feeling.",
    price: 1.99,
  },
  {
    id: 2,
    src: "./assets/confused.png",
    alt: "Confused man",
    name: "Confusion",
    description: "Description: Be confused with ANOTHER feeling.",
    price: -1.0,
  },
  {
    id: 3,
    src: "./assets/cry.png",
    alt: "Sad man",
    name: "Sadness",
    description: "Description: Be sad with ANOTHER feeling.",
    price: 3.99,
  },
  {
    id: 4,
    src: "./assets/disappointed.png",
    alt: "Disappointed man",
    name: "Disappointment",
    description: "Description: Be disappointed with ANOTHER feeling.",
    price: 0.0,
  },
  {
    id: 5,
    src: "./assets/disgusted.png",
    alt: "Disgusted man",
    name: "Disgust",
    description: "Description: Be disgusted with ANOTHER feeling.",
    price: 5.87,
  },
];
