export const products = [
  {
    id: 1,
    src: "/angry.png",
    alt: "Angry man",
    name: "Angry",
    description: "Description: Be angry with ANOTHER feeling.",
    price: "$1.99",
  },
  {
    id: 2,
    src: "/confused.png",
    alt: "Confused man",
    name: "Confused",
    description: "Description: Be confused with ANOTHER feeling.",
    price: "$0.00",
  },
  {
    id: 3,
    src: "/cry.png",
    alt: "Sad man",
    name: "Sad",
    description: "Description: Be sad with ANOTHER feeling.",
    price: "$3.99",
  },
  {
    id: 4,
    src: "/disappointed.png",
    alt: "Disappointed man",
    name: "Disappointed",
    description: "Description: Be disappointed with ANOTHER feeling.",
    price: "$99.99",
  },
  {
    id: 5,
    src: "/disgusted.png",
    alt: "Disgusted man",
    name: "Disgusted",
    description: "Description: Be disgusted with ANOTHER feeling.",
    price: "$5.87",
  },
];
